/**
 * package gussinku.dropwizard.microservice;
 * <p>
 * import gussinku.dropwizard.microservice.resources.CompanyProfileResource;
 * import io.dropwizard.jersey.setup.JerseyEnvironment;
 * import io.dropwizard.setup.Environment;
 * import org.junit.Before;
 * import org.junit.jupiter.api.Test;
 * <p>
 * /*
 * This Java source file was generated by the Gradle 'init' task.
 * public class AppTest {
 * private final Environment environment = mock(Environment.class);
 * private final JerseyEnvironment jersey = mock(JerseyEnvironment.class);
 * private final App application = new App();
 * private final Config config = new Config();
 *
 * @Before public void setup() throws Exception {
 * config.setDefaultName("Lucas");
 * when(environment.jersey()).thenReturn(jersey);
 * }
 * @Test public void buildsAThingResource() throws Exception {
 * application.run(config, environment);
 * <p>
 * verify(jersey).register(isA(CompanyProfileResource.class));
 * }
 * }
 **/
/**public class AppTest {
 private final Environment environment = mock(Environment.class);
 private final JerseyEnvironment jersey = mock(JerseyEnvironment.class);
 private final App application = new App();
 private final Config config = new Config();

 @Before public void setup() throws Exception {
 config.setDefaultName("Lucas");
 when(environment.jersey()).thenReturn(jersey);
 }

 @Test public void buildsAThingResource() throws Exception {
 application.run(config, environment);

 verify(jersey).register(isA(CompanyProfileResource.class));
 }
 }**/
