

/**
 * This Java source file was generated by the Gradle 'init' task.
 */
/**public class AppTest {
 private final Environment environment = mock(Environment.class);
 private final JerseyEnvironment jersey = mock(JerseyEnvironment.class);
 private final App application = new App();
 private final Config config = new Config();

 @Before public void setup() throws Exception {
 config.setMyParam("yay");
 when(environment.jersey()).thenReturn(jersey);
 }

 @Test public void buildsAThingResource() throws Exception {
 application.run(config, environment);

 verify(jersey).register(isA(CompanyProfileResource.class));
    }
}**/
